### ISSUE TITLE
App Installer failed to install dependencies

### ISSUE THREAD

**Issue by mediaexplorer74** [MaKrotos/Music-M#41]
Hi MaKrotos,
today I tried to install your buatuful Misic-M app.

Result:
![image](https://github.com/MaKrotos/Music-M/assets/12032735/55566073-82a2-4470-8ea8-9e6745d48849)

Is this WPF or UWP app? =)

Best,
[m][e]

**Comment by MaKrotos** [comment]
This is a WinUI3 application. I don't know why you were unable to install my application. AppInstaller, pre-installed in Windiws 10/11, should automatically download the necessary libraries when installed via the package.

**Comment by MaKrotos** [comment]
Try New [Installer](https://github.com/MaKrotos/Music-M/releases/download/0.1.5.6/Setup.exe)

**Comment by MaKrotos** [comment]
Try new [Installer](https://github.com/MaKrotos/Music-M/releases/download/0.1.5.6/Setup.VK.M.exe)

**Comment by mediaexplorer74** [comment]
> Try new [Installer](https://github.com/MaKrotos/Music-M/releases/download/0.1.5.6/Setup.VK.M.exe)

Wow, new release? Thank you!

Ohhh... no success:
![shot01](https://github.com/MaKrotos/Music-M/assets/12032735/b111db42-f0d5-491f-958c-5b0265b1118f)
![shot02](https://github.com/MaKrotos/Music-M/assets/12032735/da826f4d-aa56-4120-ae7e-9b209226ce5b)
![shot03](https://github.com/MaKrotos/Music-M/assets/12032735/cc445ac3-4bf2-4006-81a4-123dc94a21da)

I think my big problem is very old 12-year notebook and special (reduced) Windows 10 Tini 2H22 without some inportant system components...

**Comment by mediaexplorer74** [comment]
I decided to cancel Music-M experiments... I'll continue to use my own MeridianVK fork.

**Comment by MaKrotos** [comment]
You can try installing Music-M via PowerShell with the command:
```Add-AppxPackage -Path C:\\temp\\filename.msix```
In this case, he can tell you what is missing to install it. And I think that then we can find a solution.

**Comment by mediaexplorer74** [comment]
> filename.msix

Ok. I tried to install it via PS. Result:
![image](https://github.com/MaKrotos/Music-M/assets/12032735/cd5d9553-1cf0-4e07-a400-1fc22669c96d)

**Comment by MaKrotos** [comment]
Later I will include WindowsAppRuntime checking and installation in the installer <3
