### ISSUE TITLE
ошибка Windows 10

### ISSUE THREAD

**Issue by vpreparate** [MaKrotos/Music-M#48]
Не удалось проверить сертификат издателя этого пакета приложения. Обратитесь к системному администратору или разработчику приложения, чтобы получить новый сертификат с проверенными сертификатами. Корневой сертификат и все непосредственные сертификаты подписи в пакете приложения должны быть проверены (0x800B010A)
_____ почему именно пакет надо ставить? 
разве нельзя без этого обойтись?

**Comment by MaKrotos** [comment]
У сертификата разработчика видимо истёк срок действия. Придётся мне вручную его перевыпустить и выкатить обновление приложения

Не думал, забыл, что до этого может дойти.

Без пакета не удалось обойтись.
Решение сделать именно пакет было принято для бесшовного удобного обновления

И автоудаления всего мусора из приложения при его сносе.

**Comment by MaKrotos** [comment]
Выпустил обновление с новым сертификатом.

Теперь через установщик должно встать.

**Comment by vpreparate** [comment]
но всё равно очень круто сделали наверно лучший клиент для ВК со всего что есть на гите....
если Будет время хотелось бы увидеть отдельные окна для авто сбора информации:
- что нибудь типо паука который ищет интересные посты, музыку, группы
- медленную (против капчи) выгрузку всех друзей или групп пользователя
- мессенджер 
- было бы круто автопостинг или добавление в группы или в друзья (но здесь аккаунт наверно будет быстро отлетать)
- окошко для возможной капчи
- было бы круто если можно было добавлять список номеров потом их добавлять в контакты и собирать информацию со страниц по номерам из файла
- или выгружать по ключевым словам из файла группы с музыкой или полный список возможных песен типо локального архива где уже можно прослушать и добавить их
_____ может что нибудь Вам понравиться но всё равно, что уже есть, это очень круто

**Comment by MaKrotos** [comment]
Клиент чисто для музыки.

Другое не планируется.

Для автопостинга, по таймер в вк, у меня есть приватный ТГ бот.

Почтинг через него также удобен как Почтинг через ТГ

**Comment by vpreparate** [comment]
всё равно пишет нет доверия к сертификату та же ошибка

**Comment by MaKrotos** [comment]
Через пакет пытаетесь установить или через установщик?

**Comment by vpreparate** [comment]
вот через Вашу обнову:
VK.UI3.Package._0.2.1.3_x64.msix

**Comment by MaKrotos** [comment]
Установщик должен подцепить новый сертификат

**Comment by MaKrotos** [comment]
https://github.com/MaKrotos/Music-M/releases/download/0.2.0.5/Setup.FULL.exe

**Comment by MaKrotos** [comment]
Установщик просто нет смысла перевыпускать часто. Сам цепляет последнюю версию

**Comment by vpreparate** [comment]
появилась кнопка установить но приложение не ставится очень долго жду окно пакета исчезает а сам установщик нет

**Comment by MaKrotos** [comment]
Кажется, установщик сам не закрывается просто. Попробуйте найти VK в меню пуск через поиск

**Comment by vpreparate** [comment]
нет нету его

**Comment by MaKrotos** [comment]
Значит теперь через пакет попробуйте установить. Думаю сертификат поставился в систему.

Второй раз сообщают о подобном поведении. Не знаю с чем это может быть связано.

Возможно Вам придётся ставить обновления ручками, пока я не разберусь что с этим можно сделать.

**Comment by vpreparate** [comment]
аааа да я вспомнил у меня китайское имя пользователя поэтому пакеты не ставятся
имя на кириллице + восклицательный знак
может поэтому?

**Comment by vpreparate** [comment]
если получится бинарник собрать буду признателен отдельный буду рад
или придётся оффициальной первой версии ждать?

**Comment by MaKrotos** [comment]
Как я уже написал ранее, решение о пакетах было принято не просто так.

А все насущие проблемы с установкой постараюсь решить в будущем.

**Comment by MaKrotos** [comment]
Если напишешь в тг, в лс
Сможем вместе разобраться в чем косяк и как исправить ❤️

**Comment by vpreparate** [comment]
у меня ни wsl ни некоторые SDK не ставятся из-за моего имени пользователя а поменять у меня не получается: я один раз поменял меня и не туда и не сюда не пускало.... Да я понимаю что обновления важны но я не люблю обновлять код ... просто подожду первой версии - _ - звезду и на обновления подписался

**Comment by MaKrotos** [comment]
Все ещё не получилось установить?

**Comment by vpreparate** [comment]
да .... скорее всего не получится (с таким именем пользователя)

**Comment by MaKrotos** [comment]
А можете прислать имя? И написать в тг, в общем, для исследования проблемы и её решения.

Я сам создал пользователя с кириллицей и все установилось нормально.
